# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a72b584206c7185caa8bf1606fe63c64e1bf16619eb605588847de169f723144f54fd373127be4c7e7e2dfd8348779cd350d39e50670cedf6acc10cd6db26162

test:
  secret_key_base: 8a28282d54b6c4ffaf3ff7719c0e3eaa5acd1f0a84a43e63e2d5fe04b02e96a9516de13fd1739a4ae047d69c6d02b92a630a603bde9ca5db114f04cb62207e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
